#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Category {
    Workspace,
    Tab,
    Pane,
    Application,
    Custom,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Invocation {
    Herdr(Vec<String>),
    DocumentationOnly,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PaletteItem {
    pub id: String,
    pub title: String,
    pub category: Category,
    pub description: String,
    pub aliases: Vec<String>,
    pub shortcuts: Vec<String>,
    pub invocation: Invocation,
}

pub fn default_items() -> Vec<PaletteItem> {
    vec![
        action(
            "new_workspace",
            "New workspace",
            Category::Workspace,
            "Create and focus a new workspace",
            &["workspace", "create"],
            &["prefix+shift+n"],
            &["workspace", "create", "--focus"],
        ),
        action(
            "new_tab",
            "New tab",
            Category::Tab,
            "Create and focus a new tab",
            &["tab", "create"],
            &["prefix+c"],
            &["tab", "create", "--focus"],
        ),
        documentation(
            "previous_tab",
            "Previous tab",
            "Focus the previous tab",
            &["tab", "previous"],
            &["prefix+p"],
            Category::Tab,
        ),
        documentation(
            "next_tab",
            "Next tab",
            "Focus the next tab",
            &["tab", "next"],
            &["prefix+n"],
            Category::Tab,
        ),
        action(
            "focus_pane_left",
            "Focus pane left",
            Category::Pane,
            "Focus the pane to the left",
            &["pane", "left"],
            &["prefix+h"],
            &["pane", "focus", "--direction", "left", "--current"],
        ),
        action(
            "focus_pane_down",
            "Focus pane down",
            Category::Pane,
            "Focus the pane below",
            &["pane", "down"],
            &["prefix+j"],
            &["pane", "focus", "--direction", "down", "--current"],
        ),
        action(
            "focus_pane_up",
            "Focus pane up",
            Category::Pane,
            "Focus the pane above",
            &["pane", "up"],
            &["prefix+k"],
            &["pane", "focus", "--direction", "up", "--current"],
        ),
        action(
            "focus_pane_right",
            "Focus pane right",
            Category::Pane,
            "Focus the pane to the right",
            &["pane", "right"],
            &["prefix+l"],
            &["pane", "focus", "--direction", "right", "--current"],
        ),
        action(
            "split_vertical",
            "Split pane vertically",
            Category::Pane,
            "Split the current pane to the right and focus the new pane",
            &["pane", "split", "right"],
            &["prefix+v"],
            &[
                "pane",
                "split",
                "--current",
                "--direction",
                "right",
                "--focus",
            ],
        ),
        action(
            "split_horizontal",
            "Split pane horizontally",
            Category::Pane,
            "Split the current pane downward and focus the new pane",
            &["pane", "split", "down"],
            &["prefix+minus"],
            &[
                "pane",
                "split",
                "--current",
                "--direction",
                "down",
                "--focus",
            ],
        ),
        action(
            "swap_pane_left",
            "Swap pane left",
            Category::Pane,
            "Swap the current pane with the pane to the left",
            &["pane", "swap", "left"],
            &["prefix+shift+h"],
            &["pane", "swap", "--direction", "left", "--current"],
        ),
        action(
            "swap_pane_down",
            "Swap pane down",
            Category::Pane,
            "Swap the current pane with the pane below",
            &["pane", "swap", "down"],
            &["prefix+shift+j"],
            &["pane", "swap", "--direction", "down", "--current"],
        ),
        action(
            "swap_pane_up",
            "Swap pane up",
            Category::Pane,
            "Swap the current pane with the pane above",
            &["pane", "swap", "up"],
            &["prefix+shift+k"],
            &["pane", "swap", "--direction", "up", "--current"],
        ),
        action(
            "swap_pane_right",
            "Swap pane right",
            Category::Pane,
            "Swap the current pane with the pane to the right",
            &["pane", "swap", "right"],
            &["prefix+shift+l"],
            &["pane", "swap", "--direction", "right", "--current"],
        ),
        action(
            "zoom",
            "Zoom pane",
            Category::Pane,
            "Toggle zoom for the current pane",
            &["pane", "zoom"],
            &["prefix+z"],
            &["pane", "zoom", "--current"],
        ),
        documentation(
            "close_pane",
            "Close pane",
            "Close the current pane",
            &["pane", "close"],
            &["prefix+x"],
            Category::Pane,
        ),
        documentation(
            "help",
            "Help",
            "Show Herdr's keyboard shortcut guide",
            &["keyboard", "shortcuts"],
            &["prefix+?"],
            Category::Application,
        ),
        documentation(
            "settings",
            "Settings",
            "Open Herdr settings",
            &["preferences", "config"],
            &["prefix+s"],
            Category::Application,
        ),
        documentation(
            "copy_mode",
            "Copy mode",
            "Enter copy mode",
            &["copy", "scrollback"],
            &["prefix+["],
            Category::Application,
        ),
        documentation(
            "resize_mode",
            "Resize mode",
            "Enter pane resize mode",
            &["resize", "pane"],
            &["prefix+r"],
            Category::Application,
        ),
        documentation(
            "detach",
            "Detach",
            "Detach from the current Herdr session",
            &["session", "leave"],
            &["prefix+q"],
            Category::Application,
        ),
    ]
}

pub(crate) fn documentation(
    id: &str,
    title: &str,
    description: &str,
    aliases: &[&str],
    shortcuts: &[&str],
    category: Category,
) -> PaletteItem {
    PaletteItem {
        id: id.into(),
        title: title.into(),
        category,
        description: description.into(),
        aliases: aliases.iter().map(|value| (*value).into()).collect(),
        shortcuts: shortcuts.iter().map(|value| (*value).into()).collect(),
        invocation: Invocation::DocumentationOnly,
    }
}

fn action(
    id: &str,
    title: &str,
    category: Category,
    description: &str,
    aliases: &[&str],
    shortcuts: &[&str],
    argv: &[&str],
) -> PaletteItem {
    PaletteItem {
        id: id.into(),
        title: title.into(),
        category,
        description: description.into(),
        aliases: aliases.iter().map(|value| (*value).into()).collect(),
        shortcuts: shortcuts.iter().map(|value| (*value).into()).collect(),
        invocation: Invocation::Herdr(argv.iter().map(|value| (*value).into()).collect()),
    }
}
