import type { Invocation, PaletteItem } from "./types";
const entry=(id:string,title:string,category:PaletteItem["category"],description:string,icon:string,key:string,invocation:Invocation):PaletteItem=>({id,title,category,description,icon,aliases:[],shortcuts:[key],invocation});
const action=(id:string,title:string,category:PaletteItem["category"],description:string,icon:string,shortcut:string,argv:string[]):PaletteItem=>entry(id,title,category,description,icon,shortcut,{kind:"herdr",argv});
const shortcut=(id:string,title:string,category:PaletteItem["category"],description:string,icon:string,key:string):PaletteItem=>entry(id,title,category,description,icon,key,{kind:"shortcut"});
export const defaultItems=():PaletteItem[]=>[
 action("new_workspace","New workspace","Workspace","Create and focus a workspace","◇","prefix+shift+n",["workspace","create","--focus"]),
 action("new_tab","New tab","Tabs","Create and focus a tab","▣","prefix+c",["tab","create","--focus"]),
 entry("previous_tab","Previous tab","Tabs","Focus the previous tab","←","prefix+p",{kind:"focus-tab",step:-1}), entry("next_tab","Next tab","Tabs","Focus the next tab","→","prefix+n",{kind:"focus-tab",step:1}),
 action("focus_pane_left","Focus pane left","Panes","Focus the pane to the left","←","prefix+h",["pane","focus","--direction","left","--current"]), action("focus_pane_down","Focus pane down","Panes","Focus the pane below","↓","prefix+j",["pane","focus","--direction","down","--current"]), action("focus_pane_up","Focus pane up","Panes","Focus the pane above","↑","prefix+k",["pane","focus","--direction","up","--current"]), action("focus_pane_right","Focus pane right","Panes","Focus the pane to the right","→","prefix+l",["pane","focus","--direction","right","--current"]),
 action("split_vertical","Split pane right","Panes","Split the current pane side by side","▯","prefix+v",["pane","split","--current","--direction","right","--focus"]), action("split_horizontal","Split pane down","Panes","Split the current pane stacked","▤","prefix+minus",["pane","split","--current","--direction","down","--focus"]), action("zoom","Zoom pane","Panes","Toggle focused pane zoom","⌕","prefix+z",["pane","zoom","--current"]), entry("close_pane","Close pane","Panes","Close the focused pane","×","prefix+x",{kind:"close-pane"}),
 shortcut("help","Keyboard shortcuts","Herdr","Show Herdr's shortcut guide","?","prefix+?"), shortcut("settings","Settings","Herdr","Open Herdr settings","⚙","prefix+s"), shortcut("copy_mode","Copy mode","Herdr","Enter copy mode","▧","prefix+["), shortcut("detach","Detach","Herdr","Leave the current Herdr session","↗","prefix+q")
];
